import Head from 'next/head'
// import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import FormComponent from '../components/FormComponent'
import LogosComponent from '../components/LogosComponent'
// import NavComponent from '../components/NavComponent'

export default function Home() {
  const [theme, setTheme] = useState('light');
  console.log(theme)
  const switchTheme = () => {
    const newTheme = theme === 'light' ? 'dark' : 'light';
    setTheme(newTheme);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={theme}>
        {/* nav */}
        {/* <NavComponent setMode={switchTheme} /> */}
        <div className="container-fluid d-flex py-4 px-5">
          <div className="d-flex me-auto">
            <a className="navbar-brand" href="#">
            {theme === 'light' ?
                <img src="/logo_light.png" alt="" width="100" height="auto" />
                :
                <img src="/logo_dark.png" alt="" width="100" height="auto" />
            }
            </a>
          </div>
          <div onClick={switchTheme} theme={theme} className="btn btn-outline-secondary">
              {theme === 'light' ? 
              <div className="d-flex justify-content-center align-items-center">
                <img src="/img/icons/mooon.svg" width="20px" className="me-2" />
                <span className="m-0">dark</span>
                </div> : 
                <div className="d-flex justify-content-center align-items-center">
                <img src="/img/icons/sun.svg" width="20px" className="me-2" />
                <span className="m-0">light</span>
              </div>
              }
          </div>
        </div>

        <div className="container-fluid">
          <div className="row min-vh-100 p-5">
            <div className="col-lg-6 d-flex flex-column justify-content-start align-items-start pe-5">
              <h1 className="mb-0">See Dash in Action</h1>
              <h5 className="sub-heading pb-3 pt-2 pe-3">Thank you for your interest in Dash Enterprise. We'll be in touch soon to schedule a demo.</h5>
              {/* list */}
              <ul className="list pe-0 pe-lg-4">
                <li>Culpa ullamco ipsum consequat nisi qui non veniam quis deserunt sit aute cillum ullamco.</li>
                <li>Culpa ullamco ipsum consequat nisi qui non veniam quis deserunt sit aute cillum ullamco.</li>
                <li>Culpa ullamco ipsum consequat nisi qui non veniam quis deserunt sit aute cillum ullamco.</li>
              </ul>
            </div>
            {/* ghost spacer */}
            <div className="col-lg-6 d-none d-lg-flex flex-column justify-content-start align-items-start p-5 my-4 my-lg-0">
            </div>

            <FormComponent formClass={ theme === 'light' ? 'bg-white border-light' : 'bg-dark border-dark'} />

          

            {/* image desktop */}
            <div className="col-lg-6 d-none d-lg-flex flex-column justify-content-center align-items-center">
              <img className="w-100 rounded" src="/img/image.png" />
            </div>

            {/* image mobile */}
            <div className="col-lg-6 d-flex d-lg-none flex-column justify-content-center align-items-center">
              <img className="w-100 rounded position-relative" style={{ marginTop: '-60px', zIndex: '0' }} src="/img/image.png" />
            </div>

            {/* logos */}
            <LogosComponent />
          </div>
        </div>
      </main>

          {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
        </div>
        )
      }
